auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 60s       # Increased from default 30s
  http_server_write_timeout: 60s      # Increased from default 30s

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100         # Doubled cache size for better performance
  max_retries: 3
  parallelise_shardable_queries: true

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Minimal retention - 7 days to conserve space/memory
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 72h  # 3 days
  ingestion_rate_mb: 2      # Reduced for memory constraints
  query_timeout: 60s             # Increased from default 30s
  max_query_parallelism: 4       # Allow more parallel queries
  max_query_series: 10000        # Increased series limit
  max_query_lookback: 24h        # Allow looking back 24 hours
  max_streams_per_user: 1000     # Reasonable limit for security monitoring
  max_line_size: 256KB           # Increased line size limit
  max_entries_limit_per_query: 10000  # More entries per query
  ingestion_burst_size_mb: 4
  per_stream_rate_limit: 1MB
  per_stream_rate_limit_burst: 5MB
  max_global_streams_per_user: 500
  allow_structured_metadata: false

analytics:
  reporting_enabled: false

# Memory optimizations for constrained environment
target: all
