auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 32  # Very small cache

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# AGGRESSIVE retention - 3 days only for server deployment
table_manager:
  retention_deletes_enabled: true
  retention_period: 72h  # 3 days only
  deletion_mode: filter-only

# STRICT limits to prevent disk/memory issues
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 24h  # Very strict - 1 day
  ingestion_rate_mb: 1      # Very low ingestion rate
  ingestion_burst_size_mb: 2
  per_stream_rate_limit: 512KB  # Small streams
  per_stream_rate_limit_burst: 2MB
  max_line_size: 32768     # 32KB max line size
  max_streams_per_user: 500   # Reduced streams
  max_global_streams_per_user: 250
  allow_structured_metadata: false

# Compactor runs more frequently for cleanup
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m  # Every 10 minutes
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

analytics:
  reporting_enabled: false

target: all
