auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 50  # Reduced cache for minimal deployment

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Minimal retention - 7 days to conserve space/memory
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 72h  # 3 days
  ingestion_rate_mb: 2      # Reduced for memory constraints
  ingestion_burst_size_mb: 4
  per_stream_rate_limit: 1MB
  per_stream_rate_limit_burst: 5MB
  max_line_size: 65536     # Smaller line size
  max_streams_per_user: 1000  # Reduced streams
  max_global_streams_per_user: 500
  allow_structured_metadata: false

analytics:
  reporting_enabled: false

# Memory optimizations for constrained environment
target: all
