server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Suricata Fast Log - Basic alerts
  - job_name: suricata-fast
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          log_type: fast
          environment: campus-sim
          __path__: /var/log/campus-sim/suricata/fast.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{2}/\d{2}/\d{4}-\d{2}:\d{2}:\d{2}\.\d+)\s+\[\*\*\]\s+\[(?P<gid>\d+):(?P<sid>\d+):(?P<rev>\d+)\]\s+(?P<message>.*?)\s+\[\*\*\]\s+\[Classification:\s*(?P<classification>.*?)\]\s+\[Priority:\s*(?P<priority>\d+)\]\s+\{(?P<protocol>\w+)\}\s+(?P<src_ip>[\d\.]+):(?P<src_port>\d+)\s+->\s+(?P<dest_ip>[\d\.]+):(?P<dest_port>\d+)'
      - labels:
          gid:
          sid:
          classification:
          priority:
          protocol:
          src_ip:
          dest_ip:
      - timestamp:
          source: timestamp
          format: 02/01/2006-15:04:05.000000

  # Suricata EVE JSON - Rich structured logs
  - job_name: suricata-eve
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          log_type: eve
          environment: campus-sim
          __path__: /var/log/campus-sim/suricata/eve.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            src_ip: src_ip
            dest_ip: dest_ip
            src_port: src_port
            dest_port: dest_port
            proto: proto
            alert_signature: alert.signature
            alert_category: alert.category
            alert_severity: alert.severity
            flow_id: flow_id
      - labels:
          event_type:
          proto:
          alert_category:
          alert_severity:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Suricata Statistics
  - job_name: suricata-stats
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          log_type: stats
          environment: campus-sim
          __path__: /var/log/campus-sim/suricata/stats.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{2}/\d{2}/\d{4}-\d{2}:\d{2}:\d{2}\.\d+)\s+-\s+(?P<component>\w+)\s+-\s+(?P<message>.*)'
      - labels:
          component:
      - timestamp:
          source: timestamp
          format: 02/01/2006-15:04:05.000000

  # Zeek Connection Logs (JSON format)
  - job_name: zeek-conn
    static_configs:
      - targets:
          - localhost
        labels:
          job: zeek
          log_type: conn
          environment: campus-sim
          __path__: /var/log/campus-sim/zeek/conn.log
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            uid: uid
            src_ip: id.orig_h
            src_port: id.orig_p
            dest_ip: id.resp_h
            dest_port: id.resp_p
            proto: proto
            conn_state: conn_state
            duration: duration
            orig_bytes: orig_bytes
            resp_bytes: resp_bytes
      - labels:
          proto:
          src_ip:
          dest_ip:
          conn_state:
      - timestamp:
          source: ts
          format: Unix

  # Zeek Weird Logs
  - job_name: zeek-weird
    static_configs:
      - targets:
          - localhost
        labels:
          job: zeek
          log_type: weird
          environment: campus-sim
          __path__: /var/log/campus-sim/zeek/weird.*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<ts>\d+\.\d+)\s+.*\s+(?P<weird_name>\S+)'
      - labels:
          weird_name:
      - timestamp:
          source: ts
          format: Unix

  # System logs for context
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          environment: campus-sim
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+ \d+ \d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+?)(\[(?P<pid>\d+)\])?\:\s*(?P<message>.*)'
      - labels:
          hostname:
          service:
      - timestamp:
          source: timestamp
          format: Jan _2 15:04:05

  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          environment: campus-sim
          __path__: /var/log/docker.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            msg: msg
            container_name: attrs.name
      - labels:
          level:
          container_name:
      - timestamp:
          source: timestamp
          format: RFC3339
